name: Python Backend

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]


jobs:
  build-and-test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

    # below will be uncommented once we start setting up unit tests
    #  - name: Install Dependencies
    #    run: |
    #      python -m pip install --upgrade pip
    #      pip install -r requirements.txt
      - name: Verify Env
        run: |
          python --version
          echo "python working!"

  ai-review:
    needs: build-and-test # only runs if build-and-test is successful
    if: |
      github.event.sender.type != 'Bot' &&
      (github.event_name == 'pull_request' || github.event_name == 'issue_comment')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
    - name: PR Agent
      uses: The-PR-Agent/pr-agent@v0.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        config.model: "gemini/gemini-3.5-flash"
        config.fallback_models: '["gemini/gemini-3.1-flash-lite-preview"]'
        GOOGLE_AI_STUDIO.GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        github_action_config.auto_review: "true"
        github_action_config.auto_describe: "false"
        github_action_config.auto_improve: "false"
